### ISSUE TITLE
JSZip 2.2.0

### ISSUE THREAD

**Issue by dduponchel** [ravenac95/jszip-bower#1]
First of all, thanks for this module :)

The version 2.2.0 of JSZip is out and now has its own bower.json file.
If you don't have the time for this module anymore, @Stuk and I are willing to help :)

**Comment by nsams** [comment]
_ping_

2.4.0 released meanwhile

**Comment by ravenac95** [comment]
@dduponchel Super sorry about the delay here. I'm unregistering from bower now

**Comment by xaka** [comment]
I think we can close this one now as package name has been transferred to https://github.com/Stuk/jszip
