### ISSUE TITLE
Transfer package name to Stuk/jszip

### ISSUE THREAD

**Issue by xaka** [ravenac95/jszip-bower#2]
https://github.com/Stuk/jszip supports Bower and so there is no longer need for a transient package, which isn't even up to date. The package name transfer should be considered at this point. Right now `bower info jszip` displays `https://github.com/ravenac95/jszip-bower`.

**Comment by ravenac95** [comment]
@xaka Unregistering from bower now

**Comment by xaka** [comment]
Great! Thank you for prompt response

**Comment by ravenac95** [comment]
should be good now. let me know

**Comment by xaka** [comment]
Worked like a charm. Much appreciated!
